apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hotel-booking
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "hotel-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["hotel-api.hotel-booking.svc.cluster.local:80"]
